update checkes

diff --git a/.github/workflows/pr-files-not-allowed-files.yml b/.github/workflows/pr-files-not-allowed-files.yml
--- a/.github/workflows/pr-files-not-allowed-files.yml
+++ b/.github/workflows/pr-files-not-allowed-files.yml
@@ -13,15 +13,18 @@ jobs:
     - name: Fetch main branch
       run: git fetch origin main:main
 
-  run: |
-    errors=""
-    git diff --name-only --diff-filter=A origin/main | while IFS= read -r file; do
-      if grep -Fxq "$file" ./.github/policies/banned-files.txt; then
-        errors="${errors}File $file is not allowed with this name and path\n"
-      fi
-    done
-    if [ -n "$errors" ]; then
-      echo -e "$errors"
-      exit 1
-    fi
+    - name: Check Banned files
+      run: |
+        errors=""
+        banned_files=$(tr '[:upper:]' '[:lower:]' < ./.github/policies/banned-files.txt | xargs)
+        git diff --name-only --diff-filter=A origin/main | while IFS= read -r file; do
+          file_lower=$(echo "$file" | tr '[:upper:]' '[:lower:]' | xargs)
+          if echo "$banned_files" | grep -Fxq "$file_lower"; then
+            errors="${errors}File $file is not allowed with this name and path\n"
+          fi
+        done
+        if [ -n "$errors" ]; then
+          echo -e "$errors"
+          exit 1
+        fi
 
