just the actions

diff --git a/.github/workflows/pr-files-not-allowed-files.yml b/.github/workflows/pr-files-not-allowed-files.yml
--- a/.github/workflows/pr-files-not-allowed-files.yml
+++ b/.github/workflows/pr-files-not-allowed-files.yml
@@ -13,13 +13,15 @@ jobs:
     - name: Fetch main branch
       run: git fetch origin main:main
 
-    - name: Check Not Allowed files
-      id: check_not_allowed
-      run: |
-        git diff --name-only --diff-filter=A origin/main | while IFS= read -r file; do
-          if grep -Fxq "$file" ./.github/policies/banned-files.txt; then
-            echo "File $file is not allowed with this name and path"
-            exit 1
-          fi
-        done
+  run: |
+    errors=""
+    git diff --name-only --diff-filter=A origin/main | while IFS= read -r file; do
+      if grep -Fxq "$file" ./.github/policies/banned-files.txt; then
+        errors="${errors}File $file is not allowed with this name and path\n"
+      fi
+    done
+    if [ -n "$errors" ]; then
+      echo -e "$errors"
+      exit 1
+    fi
 
diff --git a/.github/workflows/pr-files-required-files.yml b/.github/workflows/pr-files-required-files.yml
--- a/.github/workflows/pr-files-required-files.yml
+++ b/.github/workflows/pr-files-required-files.yml
@@ -16,16 +16,20 @@ jobs:
     - name: Check Required files
       id: check_required
       run: |
+        errors=""
         while IFS= read -r file; do
           file_lower=$(echo "$file" | tr '[:upper:]' '[:lower:]')
           while IFS= read -r required_file; do
             required_file_lower=$(echo "$required_file" | tr '[:upper:]' '[:lower:]')
             if [ "$file_lower" = "$required_file_lower" ]; then
-              echo "File $file is not allowed to be deleted"
-              exit 1
+              errors="${errors}File $file is not allowed to be deleted\n"
             fi
           done < <(tr '[:upper:]' '[:lower:]' < ./.github/policies/required-files.txt)
         done
+        if [ -n "$errors" ]; then
+          echo -e "$errors"
+          exit 1
+        fi
 
 
 
